<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MAIN" Id="{f2ebe72b-7c64-48f6-9124-533eb91ffd46}">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
    fbValidateRequester_Test : FB_F_ValidateRequester_Test;
    fbBitMatrix64_Test       : FB_BitMatrix64_Test;
    fbPermissives_Test       : FB_Permissives_Test;
    fbInterlock_Test         : FB_Interlock_Test;
    fbAlarmSimple_Test       : FB_AlarmSimple_Test;
    fbAlarmLimit_Test        : FB_AlarmLimit_Test;
    fbDeviceBase_Test        : FB_DeviceBase_Test;
    fbLpfFirstOrder_Test     : FB_LPF_FirstOrder_IIR_Test;
END_VAR
]]>
    </Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();
]]>
      </ST>
    </Implementation>
  </POU>
</TcPlcObject>