<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MAIN" Id="{f2ebe72b-7c64-48f6-9124-533eb91ffd46}">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
    fbValidateRequester_Test : FB_F_ValidateRequester_Test;
    fbBitMatrix64_Test       : FB_BitMatrix64_Test;
    fbPermissives_Test       : FB_Permissives_Test;
    fbInterlock_Test         : FB_Interlock_Test;
    fbAlarmSimple_Test       : FB_AlarmSimple_Test;
    fbAlarmLimit_Test        : FB_AlarmLimit_Test;
    fbDeviceBase_Test        : FB_DeviceBase_Test;
    fbLpfFirstOrder_Test     : FB_LPF_FirstOrder_IIR_Test;
    fbDigitalOutput_Test     : FB_DigitalOutput_Test;
    fbDigitalInput_Test      : FB_DigitalInput_Test;
    fbTwoPosActuator_Test    : FB_TwoPosActuator_Test;
    fbAnalogInput_Test       : FB_AnalogInput_Test;
    fbAnalogOutput_Test      : FB_AnalogOutput_Test;
    fbAlarmThreshold_Test    : FB_AlarmThreshold_Test;
    fbAlarmDeviation_Test    : FB_AlarmDeviation_Test;
    fbStep_Test              : FB_Step_Test;
    fbStateMachine_Test      : FB_StateMachine_Test;
END_VAR
]]>
    </Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();
]]>
      </ST>
    </Implementation>
  </POU>
</TcPlcObject>